CREATE VIEW LATEST_INVENTORY AS
SELECT I.*
FROM Inventory I
         INNER JOIN (
    SELECT PRODUCTID, STOREID, MAX(TIME) AS TIME
    FROM Inventory
    WHERE TIME <= CURRENT_TIME
    GROUP BY PRODUCTID, STOREID
) T ON I.PRODUCTID = T.PRODUCTID AND I.STOREID = T.STOREID AND I.TIME = T.TIME
ORDER BY I.PRODUCTID, I.STOREID;